# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1967d5fa3c508e2a0bd20d35a40da36285cacf136861768a6bab4d437de08a5d2cd6f5f6e6d310c9161f41ab7dd6d8f28c440c0248916b7fc96de3e591e2cd49

test:
  secret_key_base: 10fde1f2caf3a20bb60e8b9bea2de96eb7e259e425cb4165aaa9320141c5ef88574f188867f6fe267e6004ddba463f6e4dc9133e50d79bea77d51b4569653e7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
